mode-n = { mode = 'isrm', keys = ['{esc}'] } # Do not remove this if you dont know what you are doing
print = { mode = 'n', keys = ['{space}{num}p'] }
yank = { mode = 'n', keys = ['yy'] }
quit = { mode = 'n', keys = ['{space}q'] }
save = { mode = 'n', keys = ['s'] }

input = { mode = 'n', keys = [':'] }

delete = { mode = 'nisrm', keys = ['{delete}'] }
remove = { mode = 'nisrm', keys = ['{backspace}'] }

left = { mode = 'nsrm', keys = [
    '{num}h',
    'h',
    '{num}{left}',
    '{left}'
] }

right = { mode = 'nsrm', keys = [
    '{num}l',
    'l',
    '{num}{right}',
    '{right}'
] }

up = { mode = 'nsrm', keys = [
    '{pageup}',
    '{num}k',
    'k',
    '{num}{up}',
    '{up}'
], set_args = [5] }

down = { mode = 'nsrm', keys = [
    '{pagedown}',
    '{num}j',
    'j',
    '{num}{down}',
    '{down}'
], set_args = [5] }

start_line = { mode = 'nisrm', keys = ['{home}'] }
end_line = { mode = 'nisrm', keys = ['{end}'] }

mode-i = { mode = 'nisrm', keys = ['i'] }
mode-s = { mode = 'nisrm', keys = ['s'] }
mode-r = { mode = 'nisrm', keys = ['r'] }
