mode-n = { mode = "nivrb", keys = "{esc}" } # Do not remove this if you dont know what you are doing
print = { mode = "n", keys = "{space}{num}p" }
remove = { mode = "nv", keys = "{space}{num}x" }
yank = { mode = "n", keys = "yy" }
quit = { mode = "n", keys = "{space}c" }
save = { mode = "n", keys = "{space}s" }
input = { mode = "nivrb", keys = ":" }
mode-i = { mode = "nivrb", keys = "i" }
mode-v = { mode = "nivrb", keys = "v" }
mode-r = { mode = "nivrb", keys = "r" }
