[package]
name = "mex-render"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui.workspace = true
rayon.workspace = true
mex-core.workspace = true
mex-buffer.workspace = true
mex-keys.workspace = true
mex-app.workspace = true
anyhow.workspace = true
ignore = "0.4.25"
regex = "1.12.2"
indexmap = "2.12.1"
